name: Go

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Verify go fmt
      run: test -z "$(go fmt ./...)"

    - name: Verify go vet
      run: test -z "$(go vet ./...)"

    - name: Test
      run: make test

    - name: Linting
      run: make lint

    - name: Build artifacts
      if: startsWith( github.ref, 'refs/tags/v' ) || github.ref == 'refs/heads/main'
      run: make artifacts

    - name: Gather release details
      if: startsWith( github.ref, 'refs/tags/v' ) && github.repository_owner == 'regclient'
      id: release_details
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VALID_RELEASE=false
        if [ -f "release.md" ] && grep -q "Release $VERSION" release.md; then
          VALID_RELEASE=true
        fi
        RELEASE_NOTES=$(cat release.md || echo release notes unavailable)
        # escape % and linefeeds
        RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
        RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
        RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=valid::${VALID_RELEASE}
        echo ::set-output name=release_notes::${RELEASE_NOTES}

    - name: Create release
      if: steps.release_details.outputs.valid == 'true'
      id: release_create
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_details.outputs.version }}
        body: ${{ steps.release_details.outputs.release_notes }}
        draft: false
        prerelease: false
        files: |
          ./artifacts/regbot-darwin-amd64
          ./artifacts/regbot-darwin-arm64
          ./artifacts/regbot-linux-amd64
          ./artifacts/regbot-linux-arm64
          ./artifacts/regbot-linux-ppc64le
          ./artifacts/regbot-linux-s390x
          ./artifacts/regbot-windows-amd64.exe
          ./artifacts/regctl-darwin-amd64
          ./artifacts/regctl-darwin-arm64
          ./artifacts/regctl-linux-amd64
          ./artifacts/regctl-linux-arm64
          ./artifacts/regctl-linux-ppc64le
          ./artifacts/regctl-linux-s390x
          ./artifacts/regctl-windows-amd64.exe
          ./artifacts/regsync-darwin-amd64
          ./artifacts/regsync-darwin-arm64
          ./artifacts/regsync-linux-amd64
          ./artifacts/regsync-linux-arm64
          ./artifacts/regsync-linux-ppc64le
          ./artifacts/regsync-linux-s390x
          ./artifacts/regsync-windows-amd64.exe

    - name: Save artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: ./artifacts/
        retention-days: 7
